app:
  debug: false
  addr: :8080


db:
  host: 127.0.0.1
  port: 3306
  database: aries
  username: root
  password: a8968640
  debug: false

clickhouse:
  driver: clickhouse
  host: 127.0.0.1
  port: 9000
  database: horizon
  username: default
  password:
  debug: false
